# Generated by Django 3.2.14 on 2022-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.CharField(blank=True, default='', max_length=1000)),
                ('type', models.CharField(choices=[('warning', 'warning'), ('promote', 'promote')], default='warning', max_length=100)),
                ('alert', models.CharField(choices=[('default', 'default'), ('global', 'global')], default='default', max_length=100)),
            ],
        ),
    ]
