# Generated by Django 3.2.14 on 2022-10-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalmessages', '0002_auto_20221013_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalmessage',
            old_name='alert',
            new_name='all_pages',
        ),
        migrations.AlterField(
            model_name='globalmessage',
            name='type',
            field=models.CharField(choices=[('Warning', 'warning'), ('Notice', 'notice')], default='warning', max_length=100),
        ),
    ]
