# Generated by Django 3.2.14 on 2022-10-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalmessages', '0003_auto_20221013_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmessage',
            name='type',
            field=models.CharField(choices=[('warning', 'Warning'), ('notice', 'Notice')], default='warning', max_length=100),
        ),
    ]
