# Generated by Django 3.2.14 on 2022-10-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalmessages', '0004_alter_globalmessage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmessage',
            name='hub_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalmessage',
            name='inova',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalmessage',
            name='insurance_hunter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalmessage',
            name='pc_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalmessage',
            name='smart_coverage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalmessage',
            name='all_pages',
            field=models.BooleanField(default=False),
        ),
    ]
