# Generated by Django 3.2.14 on 2022-10-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalmessages', '0005_auto_20221014_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalmessage',
            name='all_pages',
        ),
    ]
