# Generated by Django 3.2.14 on 2022-10-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalmessages', '0006_remove_globalmessage_all_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmessage',
            name='optional',
            field=models.CharField(choices=[('default', 'Default'), ('all-pages', 'All Pages')], default='default', max_length=100),
        ),
    ]
